version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_test_image:4
    networks:
      - network
    volumes:
      - static-volume:/home/django_1/pinterest/staticfiles
      - media-volume:/home/django_1/pinterest/media
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 111
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: 111

networks:
  network:

volumes:
  static-volume:
  media-volume:
  database-volume:


