# Generated by Django 4.1 on 2022-08-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nicname',
            new_name='nickname',
        ),
    ]
